create table users (
    id serial, 
    name varchar(50), 
    email varchar(75), 
    picture text,
    auth0_id text unique primary key,
    credit integer,
    wins integer,
    games integer,
    color varchar(30));

create table game_table (
    socket_id text,
    auth0_id varchar(25) ,
    foreign key (auth0_id) references users(auth0_id),
    bet integer,
    win boolean
);


create table deck (altimage text, image text, value integer, code varchar(3));
insert into deck (image, altimage, value, code) values
('https://deckofcardsapi.com/static/img/AS.png', '/images/cards/AS.png', 14, 'AS'),
('https://deckofcardsapi.com/static/img/AD.png', '/images/cards/AD.png', 14, 'AD'),
('https://deckofcardsapi.com/static/img/AC.png', '/images/cards/AC.png', 14, 'AC'),
('https://deckofcardsapi.com/static/img/AH.png', '/images/cards/AH.png', 14, 'AH'),
('https://deckofcardsapi.com/static/img/KS.png', '/images/cards/KS.png', 13, 'KS'),
('https://deckofcardsapi.com/static/img/KD.png', '/images/cards/KD.png', 13, 'KD'),
('https://deckofcardsapi.com/static/img/KC.png', '/images/cards/KC.png', 13, 'KC'),
('https://deckofcardsapi.com/static/img/KH.png', '/images/cards/KH.png', 13, 'KH'),
('https://deckofcardsapi.com/static/img/QS.png', '/images/cards/QS.png', 12, 'QS'),
('https://deckofcardsapi.com/static/img/QD.png', '/images/cards/QD.png', 12, 'QD'),
('https://deckofcardsapi.com/static/img/QC.png', '/images/cards/QC.png', 12, 'QC'),
('https://deckofcardsapi.com/static/img/QH.png', '/images/cards/QH.png', 12, 'QH'),
('https://deckofcardsapi.com/static/img/JS.png', '/images/cards/JS.png', 11, 'JS'),
('https://deckofcardsapi.com/static/img/JD.png', '/images/cards/JD.png', 11, 'JD'),
('https://deckofcardsapi.com/static/img/JC.png', '/images/cards/JC.png', 11, 'JC'),
('https://deckofcardsapi.com/static/img/JH.png', '/images/cards/JH.png', 11, 'JH'),
('https://deckofcardsapi.com/static/img/0S.png', '/images/cards/0S.png', 10, '10S'),
('https://deckofcardsapi.com/static/img/0D.png', '/images/cards/0D.png', 10, '10D'),
('https://deckofcardsapi.com/static/img/0C.png', '/images/cards/0C.png', 10, '10C'),
('https://deckofcardsapi.com/static/img/0H.png', '/images/cards/0H.png', 10, '10H'),
('https://deckofcardsapi.com/static/img/9S.png', '/images/cards/9S.png', 9, '9S'),
('https://deckofcardsapi.com/static/img/9D.png', '/images/cards/9D.png', 9, '9D'),
('https://deckofcardsapi.com/static/img/9C.png', '/images/cards/9C.png', 9, '9C'),
('https://deckofcardsapi.com/static/img/9H.png', '/images/cards/9H.png', 9, '9H'),
('https://deckofcardsapi.com/static/img/8S.png', '/images/cards/8S.png', 8, '8S'),
('https://deckofcardsapi.com/static/img/8D.png', '/images/cards/8D.png', 8, '8D'),
('https://deckofcardsapi.com/static/img/8C.png', '/images/cards/8C.png', 8, '8C'),
('https://deckofcardsapi.com/static/img/8H.png', '/images/cards/8H.png', 8, '8H'),
('https://deckofcardsapi.com/static/img/7S.png', '/images/cards/7S.png', 7, '7S'),
('https://deckofcardsapi.com/static/img/7D.png', '/images/cards/7D.png', 7, '7D'),
('https://deckofcardsapi.com/static/img/7C.png', '/images/cards/7C.png', 7, '7C'),
('https://deckofcardsapi.com/static/img/7H.png', '/images/cards/7H.png', 7, '7H'),
('https://deckofcardsapi.com/static/img/6D.png', '/images/cards/6D.png', 6, '6D'),
('https://deckofcardsapi.com/static/img/6S.png', '/images/cards/6S.png', 6, '6S'),
('https://deckofcardsapi.com/static/img/6C.png', '/images/cards/6C.png', 6, '6C'),
('https://deckofcardsapi.com/static/img/6H.png', '/images/cards/6H.png', 6, '6H'),
('https://deckofcardsapi.com/static/img/5S.png', '/images/cards/5S.png', 5, '5S'),
('https://deckofcardsapi.com/static/img/5D.png', '/images/cards/5D.png', 5, '5D'),
('https://deckofcardsapi.com/static/img/5C.png', '/images/cards/5C.png', 5, '5C'),
('https://deckofcardsapi.com/static/img/5H.png', '/images/cards/5H.png', 5, '5H'),
('https://deckofcardsapi.com/static/img/4S.png', '/images/cards/4S.png', 4, '4S'),
('https://deckofcardsapi.com/static/img/4D.png', '/images/cards/4D.png', 4, '4D'),
('https://deckofcardsapi.com/static/img/4C.png', '/images/cards/4C.png', 4, '4C'),
('https://deckofcardsapi.com/static/img/4H.png', '/images/cards/4H.png', 4, '4H'),
('https://deckofcardsapi.com/static/img/3S.png', '/images/cards/3S.png', 3, '3S'),
('https://deckofcardsapi.com/static/img/3D.png', '/images/cards/3D.png', 3, '3D'),
('https://deckofcardsapi.com/static/img/3C.png', '/images/cards/3C.png', 3, '3C'),
('https://deckofcardsapi.com/static/img/3H.png', '/images/cards/3H.png', 3, '3H'),
('https://deckofcardsapi.com/static/img/2S.png', '/images/cards/2S.png', 2, '2S'),
('https://deckofcardsapi.com/static/img/2D.png', '/images/cards/2D.png', 2, '2D'),
('https://deckofcardsapi.com/static/img/2C.png', '/images/cards/2C.png', 2, '2C'),
('https://deckofcardsapi.com/static/img/2H.png', '/images/cards/2H.png', 2, '2H');